name: Python application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage wheel flake8-black
          pip install -r requirements.txt
      - name: Install python-pydot python-pydot-ng graphviz
        run: |
          sudo apt-get install python-pydot python-pydot-ng graphviz
      - name: Run example file
        run: |
          python example.py
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
          flake8 . --count --exit-zero --statistics
      - name: Test and coverage
        run: |
          coverage run -m pytest
          coverage html -d coverage_report
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bhc
          path: dist/
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage_report/
